[project]
name = "learning-duckdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.1",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
